name: default

on:
  push:
    branches:
      - '**'
    # paths:
    # - '**.sch'
    # - '**.kicad_pcb'
  pull_request:
    paths:
      - '**.sch'
      - '**.kicad_pcb'

jobs:
  #-----------------------------------------------------------------------------------------------------------
  # Gerbers
  #-----------------------------------------------------------------------------------------------------------
  gerbers:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: nerdyscout/kicad-exports@v2.2
      with:
      # Required - kibot config file
        config: gerbers.kibot.yaml
      # optional - prefix to output defined in config
        dir: gerbers
      # optional - schematic file
        schema: '*.sch'
      # optional - PCB design file
        board: '*.kicad_pcb'
    - name: upload results
      uses: actions/upload-artifact@v2
      with:
        name: gerbers
        path: gerbers

  #-----------------------------------------------------------------------------------------------------------
  # Docs
  #-----------------------------------------------------------------------------------------------------------
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: nerdyscout/kicad-exports@v2.2
      with:
      # Required - kibot config file
        config: docs.kibot.yaml
      # optional - prefix to output defined in config
        dir: docs
      # optional - schematic file
        schema: '*.sch'
      # optional - PCB design file
        board: '*.kicad_pcb'
    - name: upload results
      uses: actions/upload-artifact@v2
      with:
        name: docs
        path: docs

  #-----------------------------------------------------------------------------------------------------------
  # BOM
  #-----------------------------------------------------------------------------------------------------------
  bom:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: nerdyscout/kicad-exports@v2.2
      with:
      # Required - kibot config file
        config: gerbers.kibot.yaml
      # optional - prefix to output defined in config
        dir: bom
      # optional - schematic file
        schema: '*.sch'
      # optional - PCB design file
        board: '*.kicad_pcb'
    - name: upload results
      uses: actions/upload-artifact@v2
      with:
        name: bom
        path: bom